### ISSUE TITLE
FormData is not defined. Dependency missing?

### ISSUE THREAD

**Issue by salutuj** [therealparmesh/object-to-formdata#26]
Looks like dependency to form-data is missing:

ReferenceError: FormData is not defined
    at isFormData (D:\AFTERWORK\PROJ\JavaScript\SaldosPaymentTest\node_modules\object-to-formdata\index.js:42:27)
    at objectToFormData (D:\AFTERWORK\PROJ\JavaScript\SaldosPaymentTest\node_modules\object-to-formdata\index.js:46:7)
    at sendToSaldos (D:\AFTERWORK\PROJ\JavaScript\SaldosPaymentTest\index.js:33:37)

**Comment by therealparmesh** [comment]
You need to polyfill this global in your environment as it's native to the browser. This is simply a utility function.
